services:
  mail:
    build:
      context: .
      dockerfile: dockerfiles/mail.Dockerfile
    restart: unless-stopped
    ports:
      - "${IP0:?error}:${HOST_MAIL_PORT:?error}:25"
    volumes:
      - "${CERTS_PATH:?error}/:/etc/letsencrypt/:ro"
    environment:
      - POSTGRES_PASSWORD
    depends_on:
      web:
        condition: service_healthy
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: dockerfiles/web.Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_PASSWORD
      - ADMIN_SECRET

  nginx:
    build: nginx
    restart: unless-stopped
    ports:
      - "${IP0:?error}:${HOST_WEBSECURE_PORT:?error}:443"
      - "127.0.0.1:80:80"
    volumes:
      - "${CERTS_PATH:?error}/:/etc/letsencrypt/:ro"
    depends_on:
      web:
        condition: service_healthy

  db:
    image: postgres:15.2
    restart: unless-stopped
    volumes:
      - tlsrpt-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tlsrpt
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "tlsrpt"]
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 60s

volumes:
  tlsrpt-db:
    name: ${POSTGRES_VOLUME}
